### ISSUE TITLE
run regtests locally

### ISSUE THREAD

**Issue by satra** [ReproNim/testkraken#36]
since regtests rely on neurodocker and cwlrunner, can we run this locally? that may allow easier testing on larger runs with parallel execution.

**Comment by djarecka** [comment]
I test smaller runs on my laptop. Haven't tried on openmind, but should work.

**Comment by kaczmarj** [comment]
@djarecka - it won't work on openmind because docker is not available.

**Comment by djarecka** [comment]
yes, forgot completely...

**Comment by djarecka** [comment]
@satra - so not sure what do you mean actually by "locally". If you mean my laptop - it's not faster than circle, so I only run short jobs (all my toy examples)

**Comment by kaczmarj** [comment]
Testkraken can now be used on the command-line, locally or in the cloud or anywhere else!

`$ testkraken path/to/workflowdir`
